// Utility for generating shareable incident cards
import { IncidentCard } from '../data/models.js'
import { getStateRights, getDefaultRightsGuide } from '../data/stateRightsData.js'
import { openaiService } from '../services/openaiService.js'

/**
 * Generate a shareable incident card
 * @param {IncidentRecord} incidentRecord - The incident record
 * @param {Object} userState - User's state information
 * @param {Array} emergencyContacts - Emergency contacts
 * @returns {Promise<IncidentCard>} Generated incident card
 */
export async function generateIncidentCard(incidentRecord, userState = '', emergencyContacts = []) {
  try {
    // Get state-specific rights information
    const stateRights = getStateRights(userState) || getDefaultRightsGuide(userState)
    
    // Extract key rights information
    const rightsInfo = {
      state: userState,
      keyRights: [
        'You have the right to remain silent',
        'You have the right to refuse consent to searches',
        'You have the right to an attorney',
        'You have the right to record police interactions in public'
      ],
      stateSpecific: stateRights.dosDonts.dos.slice(0, 3), // Top 3 dos
      emergencyNumbers: [
        { name: 'Emergency Services', number: '911' },
        { name: 'ACLU Legal Hotline', number: '1-877-6-PROFILE' }
      ]
    }

    // Generate AI description if available
    let description = `Police interaction documented on ${new Date(incidentRecord.timestamp).toLocaleDateString()}`
    if (openaiService.isAvailable()) {
      try {
        description = await openaiService.generateIncidentDescription(incidentRecord)
      } catch (error) {
        console.warn('Failed to generate AI description:', error)
      }
    }

    // Create the incident card
    const incidentCard = new IncidentCard({
      recordId: incidentRecord.recordId,
      location: incidentRecord.location,
      timestamp: incidentRecord.timestamp,
      rightsInfo: rightsInfo,
      emergencyContacts: emergencyContacts,
      shareableUrl: null // Will be set when shared
    })

    // Add description to metadata
    incidentCard.description = description

    return incidentCard
  } catch (error) {
    console.error('Error generating incident card:', error)
    throw new Error('Failed to generate incident card')
  }
}

/**
 * Generate a text summary for sharing
 * @param {IncidentCard} incidentCard - The incident card
 * @returns {string} Text summary
 */
export function generateTextSummary(incidentCard) {
  const date = new Date(incidentCard.timestamp).toLocaleString()
  const location = incidentCard.location 
    ? `Location: ${formatLocation(incidentCard.location)}`
    : 'Location: Not specified'

  return `🚨 POLICE INTERACTION DOCUMENTED 🚨

${incidentCard.description || 'Police interaction documented'}

📅 Date/Time: ${date}
📍 ${location}

🛡️ KNOW YOUR RIGHTS:
${incidentCard.rightsInfo.keyRights.map(right => `• ${right}`).join('\n')}

📞 EMERGENCY CONTACTS:
${incidentCard.rightsInfo.emergencyNumbers.map(contact => `• ${contact.name}: ${contact.number}`).join('\n')}

Generated by Know Your Rights Buddy
#KnowYourRights #PoliceAccountability #CivilRights`
}

/**
 * Generate HTML content for sharing
 * @param {IncidentCard} incidentCard - The incident card
 * @returns {string} HTML content
 */
export function generateHTMLCard(incidentCard) {
  const date = new Date(incidentCard.timestamp).toLocaleString()
  const location = incidentCard.location 
    ? formatLocation(incidentCard.location)
    : 'Not specified'

  return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Police Interaction Documentation</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
        }
        .card {
            background: white;
            border-radius: 16px;
            padding: 24px;
            box-shadow: 0 8px 24px rgba(0,0,0,0.12);
        }
        .header {
            text-align: center;
            margin-bottom: 24px;
        }
        .title {
            color: #dc2626;
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 8px;
        }
        .subtitle {
            color: #6b7280;
            font-size: 16px;
        }
        .section {
            margin-bottom: 20px;
        }
        .section-title {
            font-weight: bold;
            color: #1f2937;
            margin-bottom: 8px;
            font-size: 18px;
        }
        .info-item {
            margin-bottom: 8px;
            color: #374151;
        }
        .rights-list {
            list-style: none;
            padding: 0;
        }
        .rights-list li {
            padding: 8px 0;
            border-bottom: 1px solid #e5e7eb;
            color: #374151;
        }
        .rights-list li:before {
            content: "🛡️ ";
            margin-right: 8px;
        }
        .emergency-list {
            list-style: none;
            padding: 0;
        }
        .emergency-list li {
            padding: 8px 0;
            color: #374151;
        }
        .emergency-list li:before {
            content: "📞 ";
            margin-right: 8px;
        }
        .footer {
            text-align: center;
            margin-top: 24px;
            padding-top: 16px;
            border-top: 1px solid #e5e7eb;
            color: #6b7280;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="card">
        <div class="header">
            <div class="title">🚨 POLICE INTERACTION DOCUMENTED</div>
            <div class="subtitle">${incidentCard.description || 'Police interaction documented'}</div>
        </div>
        
        <div class="section">
            <div class="section-title">📅 Incident Details</div>
            <div class="info-item"><strong>Date/Time:</strong> ${date}</div>
            <div class="info-item"><strong>Location:</strong> ${location}</div>
        </div>
        
        <div class="section">
            <div class="section-title">🛡️ Know Your Rights</div>
            <ul class="rights-list">
                ${incidentCard.rightsInfo.keyRights.map(right => `<li>${right}</li>`).join('')}
            </ul>
        </div>
        
        <div class="section">
            <div class="section-title">📞 Emergency Contacts</div>
            <ul class="emergency-list">
                ${incidentCard.rightsInfo.emergencyNumbers.map(contact => 
                    `<li><strong>${contact.name}:</strong> ${contact.number}</li>`
                ).join('')}
            </ul>
        </div>
        
        <div class="footer">
            Generated by <strong>Know Your Rights Buddy</strong><br>
            Empowering you with legal knowledge in your pocket
        </div>
    </div>
</body>
</html>`
}

/**
 * Format location for display
 * @param {Object|string} location - Location data
 * @returns {string} Formatted location
 */
function formatLocation(location) {
  if (typeof location === 'string') {
    return location
  }

  if (location && typeof location === 'object') {
    if (location.latitude && location.longitude) {
      return `${location.latitude.toFixed(6)}, ${location.longitude.toFixed(6)}`
    }
    if (location.address) {
      return location.address
    }
    if (location.city && location.state) {
      return `${location.city}, ${location.state}`
    }
  }

  return 'Location recorded'
}

/**
 * Create a shareable URL for the incident card
 * @param {IncidentCard} incidentCard - The incident card
 * @returns {string} Shareable URL
 */
export function createShareableURL(incidentCard) {
  const baseUrl = window.location.origin
  const cardData = encodeURIComponent(JSON.stringify({
    id: incidentCard.cardId,
    timestamp: incidentCard.timestamp,
    location: incidentCard.location,
    description: incidentCard.description
  }))
  
  return `${baseUrl}/incident/${incidentCard.cardId}?data=${cardData}`
}

/**
 * Share incident card via Web Share API or fallback
 * @param {IncidentCard} incidentCard - The incident card
 * @returns {Promise<boolean>} Share success status
 */
export async function shareIncidentCard(incidentCard) {
  const textSummary = generateTextSummary(incidentCard)
  const shareableUrl = createShareableURL(incidentCard)

  // Try Web Share API first
  if (navigator.share) {
    try {
      await navigator.share({
        title: 'Police Interaction Documentation',
        text: textSummary,
        url: shareableUrl
      })
      return true
    } catch (error) {
      if (error.name !== 'AbortError') {
        console.error('Web Share API failed:', error)
      }
    }
  }

  // Fallback to clipboard
  try {
    await navigator.clipboard.writeText(`${textSummary}\n\n${shareableUrl}`)
    return true
  } catch (error) {
    console.error('Clipboard API failed:', error)
    return false
  }
}
